apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: argo
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ingress-nginx
spec: {}
---

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: argo-events
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: argocd
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cert-manager
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: external-dns
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: gitlab-runner
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: grafana
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: prometheus
spec: {}
