clusterName: ${clusterName}
region: ${region}
# Specifies if aws-load-balancer-controller should be started in hostNetwork mode.
#
# You would require this enabled if you use alternate overlay networking for pods and
# API server unable to communicate with aws-load-balancer-controller. As an example, this is required
# if you use Calico CNI on EKS
hostNetwork: true
webhookBindPort: 30001
metricsBindAddr: ":30002"
clusterSecretsPermissions.allowAllSecrets: true
