apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hl-policies-mgmt
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: dev-team-1
  destination:
    name: ce-mgmt
    namespace: default
  source:
    path: charts/hl-policies
    repoURL: 'git@github.com:VerodaClient/argocd-charts.git'
    targetRevision: HEAD
#  annotations:
#    argocd.argoproj.io/sync-wave: "-10"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 35
      backoff:
        duration: 30s
        factor: 1
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - allowEmpty=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
#      - Validate=true
#      - CreateNamespace=true
#      - ApplyOutOfSyncOnly=true
#      - ServerSideApply=true
#      - RespectIgnoreDifferences=true
#  ignoreDifferences:
#    - group: apiextensions.k8s.io
#      kind: CustomResourceDefinition
#      name: beats.beat.k8s.elastic.co
#      jsonPointers:
#        - /spec
#    - kind: PersistentVolume
#      jsonPointers:
#        - /spec/claimRef/resourceVersion
#        - /spec/claimRef/uid
#        - /status/lastPhaseTransitionTime
