apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-cloud-installer-crb
subjects:
  - kind: ServiceAccount
    name: {{ include "calico-cloud.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: calico-cloud-installer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-ns-rbac
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calico-cloud-installer-ns-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-kube-system-rbac
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calico-cloud-installer-kube-system-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-tigera-operator-rbac
  namespace: tigera-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-cloud-installer-tigera-operator-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-tigera-operator-rbac
  namespace: tigera-operator-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-cloud-installer-tigera-operator-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-tigera-prometheus-rbac
  namespace: tigera-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calico-cloud-installer-tigera-prometheus-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- if ne "Disabled" ((.Values.installer.components).imageAssurance).state }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-tigera-image-assurance-rbac
  namespace: tigera-image-assurance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calico-cloud-installer-tigera-image-assurance-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-tigera-license-rbac
  namespace: tigera-license
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-cloud-installer-sa-creator-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-tigera-access-rbac
  namespace: tigera-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-cloud-installer-sa-creator-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-calico-system-rbac
  namespace: calico-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calico-cloud-installer-calico-system-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- if ne "Disabled" ((.Values.installer.components).securityPosture).state }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-tigera-risk-system-rbac
  namespace: tigera-risk-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calico-cloud-installer-tigera-risk-system-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if ne "Disabled" ((.Values.installer.components).runtimeSecurity).state }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cloud-installer-tigera-runtime-security-rbac
  namespace: tigera-runtime-security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calico-cloud-installer-tigera-runtime-security-role
subjects:
- kind: ServiceAccount
  name: {{ include "calico-cloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- end }}