apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico-cloud-app-of-apps
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argo-apps/calico-cloud/dev-team-1 
    repoURL: 'git@github.com:VerodaClient/argocd-charts.git'
    targetRevision: HEAD
  project: infra-apps
  syncPolicy:
    automated:
      selfHeal: true
  syncWaves:
  - name: wave1
    applications:
    - sealed-secrets
  - name: wave2
    applications:
    - client-credentials
  - name: wave3
    applications:
    - calico-cloud-crds
  - name: wave4
    applications:
    - calico-cloud

