apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcm-app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argo-apps/calico-enterprise-mcm/dev-team-1
    repoURL: 'git@github.com:VerodaClient/argocd-charts.git'
    targetRevision: HEAD
  project: infra-apps
  syncPolicy:
    automated:
      selfHeal: true
